# Generated by Django 4.2.1 on 2023-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=False, max_length=50, unique=True, verbose_name='아이디'),
        ),
    ]
